name: Build OpenWrt (Docker Image)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # 用一个现成的、预装了 OpenWrt 编译环境的镜像
      image: openwrtorg/sdk:23.05.5-armvirt-64
      options: --privileged

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Load Config & Feeds
        run: |
          cp $GITHUB_WORKSPACE/feeds.conf feeds.conf.default
          cp $GITHUB_WORKSPACE/.config .config

      - name: Update Feeds & Compile
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make -j$(nproc)

      - name: Upload Rootfs
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-Full-Rootfs
          path: bin/targets/armvirt/64/openwrt-*-rootfs.tar.gz
