name: 导出OpenWrt官方rootfs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载官方rootfs
        run: |
          wget -O OpenWrt-ARM64-Docker.tar.gz https://downloads.openwrt.org/releases/23.05.4/targets/armvirt/64/openwrt-23.05.4-armvirt-64-default-rootfs.tar.gz

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt-ARM64-Docker
          path: OpenWrt-ARM64-Docker.tar.gz
